### PR TITLE
#238: fixed extension

### LINKED ISSUE #238: downloads with software repo are lacking extension and cannot be extracted
```
Starting installation of java to /d/projects/myproject-ide/software/java from http://de-mucevolve02/files/devon-ide/software/java/11.0.4_11/java-11.0.4_11-windows.tgz
Downloading java-11.0.4_11-windows from http://de-mucevolve02/files/devon-ide/software/java/11.0.4_11/java-11.0.4_11-windows.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  185M  100  185M    0     0  3327k      0  0:00:57  0:00:57 --:--:-- 4286k

 

******** ATTENTION ********
ERROR: Unknown archive format: .4_11-windows. Can not extract /c/Users/vapadwal/Downloads/java-11.0.4_11-windows
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
```

### LINKED ISSUE #240: maven archetype-catalog.xml buggy
Maven has a catalog for archetypes e.g. to detect the latest version or for GUIs to create search and auto-completion/content-assist for archetype selection:
https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html

There is a central catalog maintained in maven central repo:
http://repo.maven.apache.org/maven2/archetype-catalog.xml

However, the process of staging releases to maven central and updating the archetype catalog seems buggy or broken. Therefore we deploy releases to maven central but the archetype catalog then does not get updated accordingly.
Currently we have released `devon4j` in version `3.1.1` providing this archetype:
http://repo.maven.apache.org/maven2/com/devonfw/java/templates/devon4j-template-server/3.1.1/

However the central archetype catalog only contains versions of that archetype until version `3.1.0`:
http://repo.maven.apache.org/maven2/archetype-catalog.xml

See also:
https://maven.apache.org/archetype/maven-archetype-plugin/specification/update-catalog.html

### PR DESCRIPTION
**Pull request by hohwille**
* fixed #238: set extension to .tgz properly for repo.
* fixed #240: workaround for maven archetype-catalog update bug

### CODE REVIEW

**Comment by hohwille** [comment]
Nice catch. Tests revealed that a new version of devon4j `3.1.1` has meanwhile been released and archetype catalogue needs to be updated.

**Comment by hohwille** [comment]
Just noticed that our submodule does not point to a sepcific git commit hash but to the latest on master. This is a nice feature but however this also means that builds are not reproducible...

**Comment by hohwille** [comment]
Also migration test fails as we do not yet cover migrations for `3.1.1`. Nice that I also automated this but somewhat nasty as well since it is blocking my one-line fix.

**Comment by vapadwal** [comment]
I have tested it by putting the above code in my local devon-ide beta 21, now the zip is getting downloaded properly but

getting the error while extracting

Starting installation of java to /d/projects/myproject-ide/software/java from http://de-mucevolve02/files/devon-ide/software/java/11.0.4_11/java-11.0.4_11-windows.tgz
Downloading java-11.0.4_11-windows.tgz from http://de-mucevolve02/files/devon-ide/software/java/11.0.4_11/java-11.0.4_11-windows.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  185M  100  185M    0     0   725k      0  0:04:22  0:04:22 --:--:--  692k
Running command: tar xf '/c/Users/vapadwal/Downloads/java-11.0.4_11-windows.tgz' -C '/d/projects/myproject-ide/updates/extracted/java'
tar: /c/Users/vapadwal/Downloads/java-11.0.4_11-windows.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

******** ATTENTION ********
ERROR: Failed to run command tar
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 2

Here the software is been download in C:\Users\vapadwal\Downloads\de-mucevolve02\_files_devon-ide_software

and it is trying to extract from dir : /c/Users/vapadwal/Downloads/

I have tried changing the below code 

line no 804
from
doExtract "${DEVON_DOWNLOAD_DIR}/${filename}" "${dir}
to
 doExtract "${download_dir}/${filename}" "${dir}

And it worked. So we need to change the above line

**Comment by hohwille** [comment]
mhm, these too smart tests are making fun of me. But it is great to have them so problems get revealed:
```
Failed to properly upgrade to devon4j 3.1.0 - final version is 3.1.1
```
So this means that the latest archetype was created with version `3.1.0` but the migrator migrated to version `3.1.1` what is a mismatch.
The question is why does `devon java create com.example.myapp` create a devon4j project in version `3.1.0` but not the latest released `3.1.1`. It seems that maven archetype catalog refresh is buggy:
```
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype [com.devonfw.java.templates:devon4j-template-server:3.1.0] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: devon4j-template-server:3.1.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.example
[INFO] Parameter: artifactId, Value: demoapp
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: package, Value: com.example.demoapp
[INFO] Parameter: packageInPathFormat, Value: com/example/demoapp
[INFO] Parameter: package, Value: com.example.demoapp
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: batch, Value: .
[INFO] Parameter: earProjectName, Value: .
[INFO] Parameter: groupId, Value: com.example
[INFO] Parameter: dbType, Value: h2
[INFO] Parameter: artifactId, Value: demoapp
```

**Comment by hohwille** [comment]
OK:
https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html
So the catalog comes from here:
http://repo.maven.apache.org/maven2/archetype-catalog.xml

I checked and indeed for `devon4j-template-server` the latest version is `3.1.0`.
As `3.1.1` has been released, this is somehow wrong.
Any ideas how this is updated?

**Comment by vapadwal** [comment]
> OK:
> https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html
> So the catalog comes from here:
> http://repo.maven.apache.org/maven2/archetype-catalog.xml
> 
> I checked and indeed for `devon4j-template-server` the latest version is `3.1.0`.
> As `3.1.1` has been released, this is somehow wrong.
> Any ideas how this is updated?

If you see here https://repo1.maven.org/maven2/com/devonfw/java/templates/devon4j-template-server/
we still don't have 3.1.1 , I think the archetype-catalog.xml get automatically updated when we have release done , 
I think its problem with sonatype, better to file an issue there

**Comment by hohwille** [comment]
> I have tried changing the below code
> 
> line no 804
> from
> doExtract "${DEVON_DOWNLOAD_DIR}/${filename}" "${dir}
> to
> doExtract "${download_dir}/${filename}" "${dir}

Hey, @vapadwal 🥇 Excellent finding and fix! Thank you so much for your support!
I will asap fix this as well. 
> And it worked. So we need to change the above line

**Comment by hohwille** [comment]
OK. Now it seems we have a real bug with git submodules.
The error that I have already fixed in `devon-ide-settings` now came back to travis build.
This is totally strange:
```
Expecting:
 <["<?xml version="1.0" encoding="UTF-8"?>",
    "<archetype-catalog xsi:schemaLocation="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0 http://maven.apache.org/xsd/archetype-catalog-1.0.0.xsd"",
    "    xmlns="http://maven.apache.org/plugins/maven-archetype-plugin/archetype-catalog/1.0.0"",
    "    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">",
    "  <archetypes>",
    "    <archetype>",
    "      <groupId>com.devonfw.java.templates</groupId>",
    "      <artifactId>devon4j-template-server</artifactId>",
    "      <version>3.1.0</version>",
    "      <repository></repository>",
    "    </archetype>",
    "  </archetypes>",
    "</archetype-catalog>"]>
to contain:
 <["      <version>3.1.1</version>"]>
but could not find:
 <["      <version>3.1.1</version>"]>
```

Here is my commit. I had already seen a previous travis build passing this point.
https://github.com/devonfw/devon-ide-settings/commit/7c11f0216f8fbf766fded238a7593a35873303d0

**Comment by hohwille** [comment]
> If you see here https://repo1.maven.org/maven2/com/devonfw/java/templates/devon4j-template-server/
we still don't have 3.1.1 , I think the archetype-catalog.xml get automatically updated when we have release done ,
I think its problem with sonatype, better to file an issue there

@vapadwal maybe you have a different Internet than I do. But I *can* see version `3.1.1`. See my description of issue #240.
Maybe you just need to force refresh your browser or click this link:
http://repo.maven.apache.org/maven2/com/devonfw/java/templates/devon4j-template-server/3.1.1/

**Comment by hohwille** [comment]
OK, nice, git submodules remain a source of pain. However, here is the explanation.
If you browse the git repo of `devon-ide` you can see the submodule here:
https://github.com/devonfw/devon-ide/tree/master/settings/src/main

It actually still is connected to a specific git commit hash:
`settings @ 728d541`

Clicking on this link and browsing to the according file reveals the old content:
https://github.com/devonfw/devon-ide-settings/blob/728d5410f8ccf4e814e9c5f6e06520787c40c17f/eclipse/archetype-catalog.xml

Locally my git is updated properly. However neither my gui client (Fork) nor the commandline shows that there is anything to commit in my local `devon-ide` git repo. 

So what is the magic trick here?
And where does that commit hash come from as it is not in my `.gitmodules` file.

**Comment by vapadwal** [comment]
> > If you see here https://repo1.maven.org/maven2/com/devonfw/java/templates/devon4j-template-server/
> > we still don't have 3.1.1 , I think the archetype-catalog.xml get automatically updated when we have release done ,
> > I think its problem with sonatype, better to file an issue there
> 
> @vapadwal maybe you have a different Internet than I do. But I _can_ see version `3.1.1`. See my description of issue #240.
> Maybe you just need to force refresh your browser or click this link:
> http://repo.maven.apache.org/maven2/com/devonfw/java/templates/devon4j-template-server/3.1.1/

yes refresh was the problem

**Pull request merged**
