### PR TITLE
#21: improve OS support

### PR DESCRIPTION
**Pull request by hohwille**
#23: proper fix for dirname of sourced script

### CODE REVIEW

**Comment by maihacke** [comment]
Some strange warning appears with the new scripts...
➜  Devon-dist_2.4.0_Linux ./update-all-workspaces 
IDE environment has been initialized.
WARNING: Could not find file '' (from variable REPLACEMENT_PATTERNS_PATH)
Please check your ide-properties from workspaces/main/development/settings
Jan 22, 2019 8:30:25 AM com.devonfw.ide.configurator.Configurator logCall
INFORMATION: com.devonfw.ide.configurator.Configurator -t workspaces/main/development/settings/eclipse/workspace -w /Users/simon/Projects/Devon-dist_2.4.0_Linux/workspaces/default -v  -u

**Comment by hohwille** [comment]
> WARNING: Could not find file '' (from variable REPLACEMENT_PATTERNS_PATH)
Please check your ide-properties from workspaces/main/development/settings

Did you check that you have a file `workspaces/main/development/settings/ide-properties`?
If yes, did it declare a variable `REPLACEMENT_PATTERNS_PATH`?

This is not the case for your settings. It is not mandatory but it would allow to configure project specific variables for replacements in IDE templates. Projects should come with this and at least an empty `replacement.properties` file as extension point. Hence the warning. You can ignore it if you have no need for it.

**Comment by maihacke** [comment]
Looks good in general, env.sh is working, Open Terminal here is working.
I did not test "Open iTerm here" and Keyboard mappigns (I don't use an external keyboard).

For now the only thing left from my side is that contents of scripts/.../system/mac ("Open Terminal here", ...) are not part of the tgz. Im wondering if this is by intent.

**Comment by hohwille** [comment]
> For now the only thing left from my side is that contents of scripts/.../system/mac ("Open Terminal here", ...) are not part of the tgz. Im wondering if this is by intent.

Nope. That is a bug. Thanks for the finding. That's what our 4-eyes review process is for. Excellent!
I will fix this.

**Comment by hohwille** [comment]
> Nope. That is a bug. Thanks for the finding. That's what our 4-eyes review process is for. Excellent!

I finally had ten minutes available so I fixed it. IMHO now complete to be merged.

**Pull request merged**
